# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  - name: tag
    value: "$(Build.BuildId)"
  - name: sourceFolder
    value: "src"
  - name: distFolder
    value: "dist"
  - name: deployDirectory
    value: "/home/team-roster-deploy/deploy_back"
  - name: currentSshEndpoint
    value: "ssh-team-roster"

stages:
  - stage: BuildArtifact
    displayName: Build image
    jobs:
      - job: CI
        displayName: Build and run tests
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSource: "spec"
              versionSpec: "20.x"

          - task: CmdLine@2
            displayName: Package install
            inputs:
              script: "npm install"
              workingDirectory: $(sourceFolder)

          - task: CmdLine@2
            displayName: Package build
            inputs:
              script: "npm run build:prod"
              workingDirectory: $(sourceFolder)

          - task: CmdLine@2
            displayName: Run unit tests
            inputs:
              script: "npm run test"
              workingDirectory: $(sourceFolder)

      - job: Deliver
        displayName: Deliver
        dependsOn: CI
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              npm install
            displayName: "npm install"
            workingDirectory: $(sourceFolder)

          - script: |
              npm run build:prod
            displayName: "npm build"
            workingDirectory: $(sourceFolder)

          - task: CopyFilesOverSSH@0
            displayName: "Copy dist to remote server"
            inputs:
              cleanTargetFolder: true
              sshEndpoint: $(currentSshEndpoint)
              contents: "$(sourceFolder)/$(distFolder)/**"
              targetFolder: $(deployDirectory)
              readyTimeout: "20000"
              delayBetweenUploads: "5"

          - task: CopyFilesOverSSH@0
            displayName: "Copy dockerfile to remote server"
            inputs:
              cleanTargetFolder: false
              sshEndpoint: $(currentSshEndpoint)
              contents: "$(sourceFolder)/Docker*"
              targetFolder: $(deployDirectory)
              readyTimeout: "20000"
              delayBetweenUploads: "5"

          - task: SSH@0
            displayName: "create docker image"
            inputs:
              sshEndpoint: $(currentSshEndpoint)
              runOptions: "inline"
              inline: |
                sudo docker build --no-cache $(deployDirectory)/$(sourceFolder) -t "team-roster-front" 2>&1
