# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  - main

resources:
  - repo: self

variables:
  - name: tag
    value: "$(Build.BuildId)"
  - name: sourceFolder
    value: "src"
  - name: distFolder
    value: "dist"
  - name: deployDirectory
    value: "/home/team-roster-deploy/deploy_back"
  - name: currentSshEndpoint
    value: "ssh-team-roster"

stages:
  - stage: BuildArtifact
    displayName: Build image
    jobs:
      - job: CI
        displayName: Build and run tests
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: NodeTool@0
            inputs:
              versionSource: "spec"
              versionSpec: "20.x"

          - task: CmdLine@2
            displayName: Package install
            inputs:
              script: "npm install"
              workingDirectory: $(sourceFolder)

          - task: CmdLine@2
            displayName: Package build
            inputs:
              script: "npm run build:prod"
              workingDirectory: $(sourceFolder)

          - task: CmdLine@2
            displayName: Run unit tests
            inputs:
              script: "npm run test"
              workingDirectory: $(sourceFolder)

      - job: Deliver
        displayName: Deliver on server
        dependsOn: CI
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: CopyFilesOverSSH@0
            displayName: "copy source to deploy directory"
            inputs:
              cleanTargetFolder: true
              sshEndpoint: $(currentSshEndpoint)
              contents: "./$(sourceFolder)/$(distFolder)/**"
              targetFolder: $(deployDirectory)
              readyTimeout: "20000"
          - task: SSH@0
            displayName: "create docker image"
            inputs:
              sshEndpoint: $(currentSshEndpoint)
              runOptions: "inline"
              inline: |
                cd $(deployDirectory)/$(sourceFolder)
                sudo docker build --no-cache . -t "team-roster-api" 2>&1
