# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: CI
    displayName: Build and run tests
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: NodeTool@0
        inputs:
          versionSource: 'spec'
          versionSpec: '20.x'
      - task: CmdLine@2
        displayName: Package install
        inputs:
          workingDirectory: src
          script: 'npm install'

      - task: CmdLine@2
        displayName: Package build
        inputs:
          workingDirectory: src
          script: 'npm run build:prod'

      - task: CmdLine@2
        displayName: Package build
        inputs:
          workingDirectory: src
          script: 'npm run test'

  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/src/Dockerfile'
        tags: |
          $(tag)
